language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
os:
  - linux
  - osx
sudo: required
dist: trusty
matrix:
  include:
    - os: linux
      python: "nightly"
    - os: linux
      python: "3.7-dev"
  allow_failures:
    - os: osx           # Python 3 not supported in Travis OSX environment
    - os: linux
      python: "nightly"
    - os: linux
      python: "3.7-dev"

notifications:
  email: false

cache:
  directories:
    - $HOME/.cache/pip

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update;
      brew tap homebrew/science;
      brew install openblas;
    else
      sudo apt-get update -qq;
      sudo apt-get install -y build-essential gfortran libatlas-base-dev liblapacke-dev;
      sudo apt-get install -y python3-dev;
    fi
  - python -V
  - travis_retry pip install --upgrade pip wheel   # get pip >= 7, which caches built packages
  - travis_wait 20 pip install -r requirements.txt
  - pip install coverage
  - pip install codecov
  - pip install pylint
install:
  - ./setup.py build_ext --inplace
script:
  - python -m unittest -v
  - coverage run --source libact --omit */tests/* setup.py test
  - coverage report
after_success:
  - pylint libact
  - codecov
